Redone from scratch; now fixed design
Cumsterdump/homework_18 pull request #1
Opened 2017-12-02 19:52 UTC by Cumsterdump

Не pixel perfect, зато ничего не едет. Исправил вёрстку на статичную и перешёл на Bootstrap. Почти всё остальное осталось без изменений - разве что меньше стало совместного использования "сеточных" и самописных классов.

2017-12-02 19:59 UTC, mlshv requested changes
Отцентруй с margin auto
![image](https://user-images.githubusercontent.com/16861579/33519254-6e96cbd2-d7b4-11e7-8c64-811c4db559d8.png)

2017-12-03 06:49 UTC, mlshv requested changes
- серый фон футера не на весь экран
- копирайт устанавливает марджины, поэтому он уже нужных 10 колонок
- две большие панели-картинки под шапкой кликабельны
- названия товаров в карточках кликабельны

2017-12-05 08:25 UTC, Cumsterdump commented
- где нужно, добавил <a>;
- фон футера занимает всю ширину страницы;
- убран горизонтальный margin у копирайта.

2017-12-05 10:52 UTC, mlshv approved these changes
Красава

2017-12-05 10:57 UTC, merged